---
  - name: Install Nginx
    apt: name=nginx state=latest

  - name: Start & Enable Nginx
    service: name=nginx state=started enabled=yes

  - name: Remove default html file created by Nginx
    shell: "rm -rf /var/www/html/*.html"

  - name: Create Nginx config
    template: src=wagtail.conf.j2 dest=/etc/nginx/sites-available/wagtail.conf
    notify:
      - nginx restart

  - name: Remove symbolic link
    file:
      path: "/etc/nginx/sites-enabled/default"
      state: absent
    notify:
      - nginx restart

  - name: Create symbolic link
    file:
      path: "/etc/nginx/sites-enabled/wagtail.conf"
      state: link
      src: "/etc/nginx/sites-available/wagtail.conf"
      force: yes
    notify:
      - nginx restart
